export default {
    GET_USER_MESSAGE: "GET_USER_MESSAGE",
    GET_USER_PLAYLIST:"GET_USER_PLAYLIST",
    GET_RECENT_PLAY:"GET_RECENT_PLAY",
    GET_RECOMMEND:"GET_RECOMMEND",
    GET_SUBLIST:"GET_SUBLIST",
    GET_DJDETAIL:"GET_DJDETAIL",
    GET_DJPROGRAM:"GET_DJPROGRAM"
}